drf-tutorial-2/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

if settings.DEBUG:
    import debug_toolbar

urlpatterns = [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

# POST URL MAPPING
urlpatterns += [
	url(r'^posts/', include('posts.urls', namespace='posts')),
    
]

# PROFILE URL MAPPING
urlpatterns += [
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),

]

# Use static to add URL mapping to server static files - LOCAL DEV ONLY

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Use media to add URL mapping to server media files - LOCAL DEV ONLY

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from .views import (
	PostListView, PostCompleteListView, PostDetailView, PostCompleteDetailView, PostCategoryListView,
	PostCreate, PostEdit, PostDelete, LogOutView,
)


# Post URL CONF
urlpatterns = [
		url(r'^$', PostListView.as_view(), name='post-home'),
		url(r'^complete/$', PostCompleteListView.as_view(), name='post-complete'),	
		url(r'^complete/(?P<pk>\d+)$', PostCompleteDetailView.as_view(), name='post-detail-complete'),
		url(r'^(?P<pk>\d+)$', PostDetailView.as_view(), name='post-detail'),
		url(r'^create/$', PostCreate.as_view(), name='post-create'),
		url(r'^(?P<pk>\d+)/edit/$', PostEdit.as_view(), name='post-edit'),
		url(r'^(?P<pk>\d+)/delete/$', PostDelete.as_view(), name='post-delete'),
		url(r'^category/$', PostCategoryListView.as_view(), name='post-all'),
		url(r'^accounts/logout/$', LogOutView.as_view(), name='logout'),
]

posts/models.py
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models
from django.db.models import Q 


class Category(models.Model):
	"""
	Learn New Things
	Life Goals
	Career
	Personal Life
	Health
	Milestone
	Adventure
	Skills
	Travel
	"""
	name = models.CharField(max_length=100, help_text="Category for the Bucketlist (e.g. Travel, Milestone, Skills")

	def __str__(self):
		return self.name


class Post(models.Model):
	title 			= models.CharField(max_length=50)
	description 	= models.TextField(max_length=1000)
	category 		= models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
	completed 		= models.BooleanField(default=False)
	date_created 	= models.DateTimeField(auto_now_add=True)
	date_updated 	= models.DateTimeField(auto_now=True)
	date_completed  = models.DateTimeField(auto_now=True, null=True, blank=True)
	image		 	= models.ImageField(upload_to='posts/%Y/%m/%d', null=True, blank=True)

	class Meta:
		ordering = ['-pk']

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('posts:post-detail', kwargs={'pk': self.pk})

posts/forms.py
from django.forms import ModelForm
from .models import Post


class PostForm(ModelForm):
	class Meta:
		model = Post
		fields = ['title', 'description', 'category', 'image']

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, RedirectView


from .models import Post, Category
from .forms import PostForm
from profiles.models import PostInstance


class PostListView(LoginRequiredMixin, ListView):
	model = Post	
	context_object_name = 'posts'
	template_name = 'post_home.html'

	def get_context_data(self, **kwargs):
		context = super(PostListView, self).get_context_data(**kwargs)

		context['categories'] = Category.objects.filter(
			Q(name__iexact='Travel') |
 			Q(name__iexact='Adventure') |
 			Q(name__iexact='Learn New Things')).distinct()

		context['travels'] = Post.objects.filter(category__name__iexact='Travel')[:6]
		context['adventures'] = Post.objects.filter(category__name__iexact='Adventure')[:6]
		context['lnts'] = Post.objects.filter(category__name__iexact='Learn New Things')[:6]
		qs = self.request.GET.get('q')
		if qs:
			context['qs'] = Post.objects.filter(title__icontains=qs)

		return context


class PostCompleteListView(LoginRequiredMixin, ListView):
	model = Post
	template_name = 'post_complete.html'

	def get_queryset(self):
		return Post.objects.filter(completed=True, user=self.request.user)

	
class PostDetailView(DetailView):
	model = Post
	context_object_name = 'posts'
	template_name = 'post_detail.html'


class PostCompleteDetailView(LoginRequiredMixin, UpdateView):
	model = Post
	fields = ['title', 'description', 'anecdote', 'category', 'completed']	
	template_name = 'post_edit.html'


class PostCreate(LoginRequiredMixin, CreateView):
	form_class = PostForm
	template_name = 'post_create.html'
	success_url = reverse_lazy('posts:post-home')

	def form_valid(self, form):
		instance =  form.save(commit=False)
		instance.user = self.request.user
		return super(PostCreate, self).form_valid(form)


class PostEdit(LoginRequiredMixin, UpdateView):
	model = Post
	template_name = 'post_edit.html'
	fields = ['title', 'description', 'category']
	

class PostDelete(LoginRequiredMixin, DeleteView):
	model = Post
	template_name = 'post_delete.html'
	success_url = reverse_lazy('posts:post-home')


class PostCategoryListView(ListView):
	model = Post
	context_object_name = 'categories'
	template_name = 'post_all.html'

	def get_queryset(self):
		cat = self.request.GET.get('q')
		return Post.objects.filter(category__name__iexact=cat)


class LogOutView(RedirectView):
	url = reverse_lazy('posts:post-home')

	def get(self, request, *args, **kwargs):
		logout(request)
		return super(LogOutView, self).get(request, *args, **kwargs)

		

posts/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <title>Posts</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
  <header>

  <nav class="navbar navbar-expand-lg navbar-light bg-faded navbar-right fixed-top" id="main-nav">
    <a class="navbar-brand" href="{%url 'posts:post-home' %}">Dashboard</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <form class="form" method="GET" action=".">
          <input type="text" placeholder="Search.." name="q" value="{{ request.GET.q }}">
          <button class="btn btn-link" type="submit">Search</button>
          </form>
        </li>
      </ul>
      <ul class="navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li class="nav-item">
          <a class="nav-link" href="{% url 'profiles:profile-detail' username=user.username %}">Dashboard</a>
        </li>        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Log out</a>
        </li>        
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="#">Sign Up</a>
        </li>        
        <li class="nav-item">
          <a class="nav-link" href="#">Log In</a>
        </li>   
        {% endif %}     
      </ul>
<!--       <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form> -->
    </div>
  </nav>
  </header>

  <div class="container-fluid">
  <!-- <div class="col-sm-4 col-md-2 d-none d-sm-block bg-light sidebar">
  {% block sidebar %} -->
  <!-- <ul class="sidebar-nav"> -->
  <!-- <ul class="nav nav-pills flex-column sidebar-nav">
    <li class="nav-item"><a href="{% url 'posts:post-home' %}">Home</a></li>
    {% if user.is_authenticated  %}
    <li class="nav-item"><a href="{% url 'posts:post-create' %}">Create</a></li>
    <li class="nav-item"><a href="{% url 'profiles:profile-detail' username=user.username %}">Dashboard</a></li>
    <li class="nav-item"><a href="{% url 'posts:post-complete' %}">Complete</a></li>
    {% endif %}
    
  </ul>
  {% endblock %}
  </div>
  </div> -->
   
    <main role="main" class="container">
    {% block content %}{% endblock %}
    </main>
  </div>
  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"></script>
  </body>
</html>

posts/templates/post_all.html
{% extends 'base.html' %}
{% block content %}


<div class="row category-custom">
  <h3>{{ category }}</h3>
</div>
  <div class="row post-custom">
	{% for category in categories %}
    <div class="card col-md-2">
        {% if category.image %}
        <img class="card-img-top" src="{{ category.image.url }}">
        {% else %}
        <img class="card-img-top">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title"><a href="{{ category.get_absolute_url }}">{{ category }}</a></h4>
        </div>
    </div>
    {% endfor %}
  </div>

{% endblock %}

posts/templates/post_complete.html
{% extends 'base.html' %}
{% block content %}


{% if post_list %}
<ul>
{% for post in post_list %}
  <li>
    <a href="{{ post.get_absolute_url }}"><h5>{{ post.title }}</h5></a>
    Posted: {{ post.date_created }}<br>
    <!-- <small>{{ post.category_is_blank }}</small><br> -->
    Completed: <strong>{{ post.date_completed }}</strong><br>
    {% if user.is_authenticated %}
    <a href="{% url 'posts:post-delete' post.pk %}">Delete</a>
    {% endif %}
  </li><hr>
{% endfor %}
</ul>
{% else %}
<p>No bucketlist fulfilled yet!</p>

{% endif %}

{% endblock %}

posts/templates/post_create.html
{% extends 'base.html' %}
{% block content %}

<h2>Create!</h2>
<form action="" method="POST">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />    
</form>

{% endblock %}

posts/templates/post_delete.html
{% extends 'base.html' %}
{% block content %}


<h2>Delete!</h2>

<p>Are you sure you want to delete this post? - <strong>{{ post.title }}</strong></p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, Delete" />
</form>


{% endblock %}

posts/templates/post_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
<div class="container detail-container">
<div class="col-sm-9 offset-sm-1">
{% if object.image %}
<img src="{{ object.image.url }}" class="img-fluid">
{% endif %}

<h4>{{ object.title }}</h4>
<p>{{ object.description }}</p>
<hr>
</div>

<!-- {% if object.completed %}
<ul>
<li>Updated: {{ object.date_created|timesince }} ago</li>
<li><strong>Anecdote: {{ object.anectdote }}</strong></li>
<li><strong>Completed: {{ object.date_completed }}</strong></li>
</ul>
{% endif %} -->

</div>
</div>

{% endblock %}

posts/templates/post_edit.html
{% extends 'base.html' %}
{% block content %}

<form action="" method="POST">

    {% csrf_token %}     
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />    
</form>

{% endblock %}

posts/templates/post_home.html
{% extends 'base.html' %}
{% block content %}

{% if qs %}

<div class="row category-custom">
  <h3>Search Results...</h3>
</div>
  <div class="row post-custom">
    {% for q in qs %}
    <div class="card col-md-2">
        {% if q.image %}
        <img class="card-img-top" src="{{ q.image.url }}">
        {% else %}
        <img class="card-img-top">
        {% endif %}
        <div class="card-body">
          <h4 class="card-title"><a href="{{ q.get_absolute_url }}">{{ q }}</a></h4>
        </div>
    </div>
    {% endfor %}

{% else %}

{% for category in categories %}

<div class="row category-custom">
  <h3>{{ category }}</h3> <h4><a href="{% url 'posts:post-all' %}?q={{category}}">({{ category.post_set.count }}+)</a></h4>
</div>
    
<!-- TRAVEL -->
  {% if category.name == 'Travel' %}
  <div class="row post-custom">
    {% for travel in travels %}
    <div class="card col-md-2">
        {% if travel.image %}
        <img class="card-img-top" src="{{ travel.image.url }}">
        {% else %}
        <img class="card-img-top">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title"><a href="{{ travel.get_absolute_url }}">{{ travel }}</a></h5>
        <div class="card-text">
          <h6 class=""><a href="{% url 'profiles:post-add' username=user.username pk=travel.pk %}">ADD</a></h6>
        </div>
        </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}

<!-- ADVENTURE -->
  {% if category.name == 'Adventure' %}
  <div class="row post-custom">
    {% for adventure in adventures %}
    <div class="card col-md-2">
        {% if adventure.image %}
        <img class="card-img-top" src="{{ adventure.image.url }}">
        {% else %}
        <img class="card-img-top">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title"><a href="{{ adventure.get_absolute_url }}">{{ adventure }}</a></h5>
          <h6 class="card-text"><a href="{% url 'profiles:post-add' username=user.username pk=adventure.pk %}">ADD</a></h6>
        </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}

<!-- LEARN NEW THINGS --> 
  {% if category.name == 'Learn New Things' %}
  <div class="row post-custom">
    {% for lnt in lnts %}
    <div class="card col-md-2">
    {% if lnt.image %}
        <img class="card-img-top" src="{{ lnt.image.url }}">
        {% else %}
        <img class="card-img-top">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title"><a href="{{ lnt.get_absolute_url }}">{{ lnt }}</a></h5>
          <h6 class="card-text"><a href="{% url 'profiles:post-add' username=user.username pk=lnt.pk %}">ADD</a></h6>
        </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}

<!-- END FOR CATEGORY IN CATEGORIES -->
{% endfor %}

<!-- END FOR QS -->
{% endif %}

{% endblock %}